# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박세환
title: Backend Developer
email: gehwan96@gmail.com
website: www.github.com/Gelloger
blog: https://velog.io/@gehwan96
blog2: https://gelog.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Gelloger

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://velog.io/@gehwan96

# About Section
# about_title: About Me
about_profile_image: images/profile2.png
about_content: | # this will include new lines to allow paragraphs
    5년차 Java & Spring Boot 백엔드 개발자로 일하고 있는 박세환입니다.
  
    쿠팡, 무신사, 배달의민족과 같은 대형 고객사가 사용하고 **월 평균 2~3억건의 발송을 처리**하는 Email 서비스에서 개발/배포/운영하고 있습니다.
    신규 서비스 Notification Hub, 친구톡 Upgrade 설계 및 개발에 참여하여 프로젝트의 시작부터 서비스 출시까지 전 과정을 경험했습니다.
  
    서비스 내 레거시 코드를 리팩토링하여 가독성 높은 코드를 작성하는 것과 팀 전체의 생산성을 높이는 것에 관심이 많습니다. 
    이를 위해 신규 입사자 개발 가이드를 작성하고 PR 템플릿을 도입했으며 서비스 장애 히스토리를 문서화하여 공유하는 등 팀 내 개발 문화를 발전시켰습니다.
  
  
    <strong>기술 스택<strong>
      - 프레임워크 - <mark>Spring Boot 2/3</mark>
      - 언어 - <mark>Java 8/11/21</mark>, <mark>Kotlin</mark>
      - 테스트 - <mark>Junit 4/5</mark>
      - 미들웨어 - <mark>RabbitMQ</mark>
      - 웹서버 - <mark>Nginx</mark>
      - DevOps - <mark>Jenkins</mark>, <mark>SonarQube</mark>, <mark>Grafana</mark>
      - DB(Hibernate) - <mark>MySQL</mark>, <mark>MongoDB</mark>, <mark>MyBatis</mark>, <mark>JPA</mark>, <mark>QueryDSL</mark>
      - 기타 - <mark>OpenAPI Specification3</mark>, <mark>Hexagonal Architecture</mark>, <mark>GitHub</mark>

content:
  - title: Company
    layout: list
    content:
      - layout: left
        title: NHN CLOUD
        link: www.nhncloud.com/kr
        sub_title: Backend Developer
        caption: 2022.02 ~ 현재
        description: | # this will include new lines to allow paragraphs    
          <strong>주요 업무<strong>
          - Email API 설계 및 개발
          - 시스템 구조 개선 작업 수행(Legacy Code Refactoring, Re-architecture 등)
          - 표준화 수행(RFC 적용): RFC 7208, RFC 6376, RFC 7489, RFC 5322
          - 발송 성능 개선
          - 서비스 운영 및 관리, 모니터링
          - **Notification Hub (2024.02 ~ 2024.12)**: Email, SMS, RCS, KTB, Push 통합 서비스 개발
          - **친구톡 Upgrade (2025.01 ~)**: 카카오 친구톡 Upgrade CBT 개발

      - title: LG CNS
        link: https://www.lgcns.com/
        sub_title: Backend Developer
        caption: 2021.01. ~ 2022.02
        description: | # this will include new lines to allow paragraphs
          <strong>주요 업무<strong>
          - 기존 모놀리스 시스템 마이크로 서비스 전환 
          - LG Uplus 전산 시스템 모바일 단말 판매 기능 개발

  - title: Experience # Title for the section
    layout: list # Layout for the section
    content:
      - title: Notification Hub 개발
        sub_title: 2023.07 ~ 2023.10, 2024.02 ~ 2024.12
        description: | # this will include new lines to allow paragraphs
          - 신규 서비스 Notification Hub 설계 및 개발 참여 
          - 첨부파일, 상세설정 API 설계 및 개발
          - API 예외 응답 다국어 처리 구조 설계 및 개발
          - Email 발송 API 개발 
          - 미터링 개발
          - 사용 기술: <mark>Hexagonal architecture</mark>, <mark>DDD</mark>, <mark>OpenAPI specification3</mark>, <mark>Kotlin, <mark>RabbitMQ</mark>, <mark>MongoDB</mark>, <mark>MySQL</mark>, <mark>Github</mark>
      - title: Email 발송 로직 리팩토링
        sub_title: 2023.11 ~ 2024.01
        description: | # this will include new lines to allow paragraphs
          Email 발송 구조 개선 작업 수행 
          - 3개 모듈에 중복 구현된 2000여 줄의 발송 로직을 리팩토링 진행
          - 절차지향적 코드를 객체지향적으로 개선하여 유지보수성 향상
          - 코드 라인 수 60% 감소 및 책임 분리를 통해 가독성 개선

      - title: Gmail 발신자 정책 변경 대응
        sub_title: 2023.11 ~ 2024.02
        description: | # this will include new lines to allow paragraphs
          2024년 2월 Gmail 발신자 정책 변경에 따른 대응 작업을 수행
          - DMARC 검증 시나리오 추가 (RFC 7489)
          - API 유효성 로직 개선 (RFC 7208)
          - 내부 시스템 점검 및 정책 변경 

      - title: 안정화 TF
        sub_title: 2023.08 ~ 2023.09
        description: | 
          팀 내에서 발생하는 장애 발생 원인을 분석하고 개선하는 업무를 수행
          - Watchdog 및 Grafana 모니터링 알람 개선
          - MDC 및 logback을 활용한 로깅 고도화
          - SonarQube 도입
          - Grafana 대시보드 시각화를 통한 운영 업무 개선 

      - title: Email 서비스 내부 개선
        sub_title: 2022.04 ~ 2023.07
        description: |
          - 인프라 이중화 작업을 수행하여 `서비스 안정성 확보`
          - 운영용 API를 개발하여 `서비스 장애 대응 시간 단축`
          - 멀티 모듈 프로젝트로 재구성 및 공통화 작업을 진행해 `코드 재사용성 강화`
          - Nginx Reverse Proxy 및 HTTP Method Blocking 설정으로 `API 무작위 공격 대응`
          - 커서 기반 조회 도입으로 `조회 API slow query 개선`
          - 내부 발송 로직을 분석 및 최적화하여 `발송량 20% 증가 및 최종 응답 soft bounce 발생 90% 감소`
          - 테스트 코드 수행 시간 지연 원인을 분석 및 개선하여 `4분 54초 → 2분 07초로 단축`
          - CI 빌드 속도를 최적화하여 `수행 시간 20% 단축`
          - 서비스 전체 테스트 코드를 JUnit 5로 마이그레이션 완료

      - title: 사내 오픈소스 starter library 개발
        sub_title: 2022.04. ~ 2022.07, 2024.10
        description: |
          - 사내 오픈소스로 외부 시스템과의 통신 검증 기능 개발
          - MongoDB, Redis 등 다양한 외부 서버 연동 지원
          - JDK 8, JDK 11, JDK 21 버전 호환성 제공
          - Autoconfiguration을 활용한 사내 오픈소스 Starter 라이브러리 개발

      - title: Ucube 시스템 개발
        sub_title: 2021.01. ~ 2022.02
        description: |
          - 모바일 단말 판매로직 개발 
          - Monolith Architecture에서 Microservice Architecture 전환 경험 
          - 사용 기술: <mark>Spring Boot</mark>, <mark>Java 11</mark>, <mark>JPA</mark>, <mark>QueryDSL</mark>

## Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
