# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박세환
title: Backend Developer
email: gehwan96@gmail.com
website: www.github.com/Gelloger
blog: https://velog.io/@gehwan96
blog2: https://gelog.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Gelloger

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://velog.io/@gehwan96

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
    안녕하세요. 백엔드 개발자로 일하고 있는 박세환입니다. 신기술과 최신 트렌드에 관심이 많고 공유하는 것을 좋아합니다.<br>
    서비스 내 레거시 코드를 리팩토링하여 가독성 있는 코드를 작성하는 것과 팀 전체의 생산성을 높이는 것에 관심이 많습니다.
  
    기술 스택 (주/부)
      - 프레임워크 - <mark>Spring Boot 2/3</mark>
      - 언어 - <mark>Java 8/11/21</mark>, <mark>Kotlin</mark>
      - 테스트 - <mark>Junit4/5</mark>
      - 미들웨어 - <mark>RabbitMQ</mark>
      - 웹서버 - <mark>Nginx</mark>
      - DevOps - <mark>Jenkins</mark>, <mark>Sonarqube</mark>, <mark>Grafana</mark>
      - DB(Hibernate) - <mark>MySQL</mark>,<mark>Mybatis</mark>, <mark>JPA</mark>, <mark>QueryDSL</mark>
      - 기타 - <mark>OpenAPI Specification3</mark>, <mark>Clean Architecture</mark>, <mark>Github</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: NHN CLOUD
        link: www.nhncloud.com/kr
        sub_title: Backend Developer
        caption: 2022.02 ~ 현재
        description: | # this will include new lines to allow paragraphs
          NHN CLOUD Email은 현재 쿠팡,무신사,배달의민족과 같은 대형 고객사가 사용하고 있는 Email 서비스입니다. <br><br>
          월 평균 2억건의 발송을 처리하고 있는 Email 서비스를 2022년 5월부터 담당하여 운영하고 있습니다. 
          <br>
          
          <strong>주요 업무<strong>
          - 고객 요구사항 분석 및 신규 기능 개발
          - 시스템 구조 개선 작업 수행(Legacy Code Refactoring, Re-architecture 등)
          - 표준화 수행(RFC 적용): RFC 7208, RFC 6376, RFC 7489, RFC 5322
          - 발송 성능 개선
          - 서비스 운영 및 관리, 모니터링

      - title: LG CNS
        link: https://www.lgcns.com/
        sub_title: Backend Developer
        caption: 2021.01. ~ 2022.02
        description: | # this will include new lines to allow paragraphs
          LG Uplus 서비스 Ucube 시스템의 단말기 판매 기능을 담당하여 개발하였습니다. <br>
          기존 모놀리스 시스템을 마이크로 서비스로 전환하는 작업을 수행하였습니다. <br>
          <br>
          
          <strong>주요 업무<strong>
          - 사내 시스템 DA#을 이용한 ERD 설계
          - Sequence Diagram 및 API 설계 진행
          - Spring Boot, Java, JPA 및 QueryDSL를 활용한 서비스 개발

  - title: Experience # Title for the section
    layout: list # Layout for the section
    content:
      - title: Notification Hub 신규 개발
        sub_title: 2024.02 ~ 현재
        description: | # this will include new lines to allow paragraphs
          신규 시스템 개발 참여
          - 첨부파일 및 상세설정 기능 개발
          - Clean architecture 및 DDD 기반의 개발 진행

      - title: Email 발송 구조 개선
        sub_title: 2023.11 ~ 현재
        description: | # this will include new lines to allow paragraphs
          Email 발송 구조 개선 작업 수행 
          - SMTP Callback 구조 개선 (mq 도입)
          - 기존 발송 관련 레거시 코드 리팩토링 수행
          - 발송 시나리오 개선

      - title: Gmail 발신자 정책 변경 대응
        sub_title: 2023.11 ~ 2023.02
        description: | # this will include new lines to allow paragraphs
          2024년 2월 Gmail 발신자 정책 변경에 따른 대응 작업을 수행
          - DMARC 검증 시나리오 추가 (RFC 7489)
          - API 유효성 로직 개선 (RFC 7208)
          - 내부 시스템 점검 및 정책 변경 

      - title: Notification Hub API 설계
        sub_title: 2023.07 ~ 2023.10
        description: | # this will include new lines to allow paragraphs
          신규 서비스 API 설계 참여
          - API 설계 진행 (상세 설정)
          - OpenAPI specification3을 이용한 API 문서화 진행

      - title: 안정화 TF
        sub_title: 2023.08 ~ 2023.09
        description: | # this will include new lines to allow paragraphs
          팀 내에서 발생하는 장애 원인을 분석하고 개선하는 업무를 수행
          - 모니터링 알람 개선
          - 전체 서비스 팀 내 공통 모듈 의존성 최신화
          - logging 카테고리 세분화를 통한 logNCrash 사용 고도화
          - sonarQube rule 적용
          - PR Template 제안 및 적용
          - Grafana 사용간 메트릭 지표 추가

      - layout: left
      - title: Email 내부 개선
        sub_title: 2023.01 ~ 2023.07
        description: | # this will include new lines to allow paragraphs
          - 인프라 이중화 작업
          - File Crafter 연동 및 SQL cursor 기반으로 변경 (성능 개선)
          - 내부 발송 로직 분석 및 성능 개선 (발송량 20% 증가)
          - Maven에서 Gradle로 마이그레이션 진행 및 멀티 모듈로 Email 프로젝트 재구성
          - 빌드 및 테스트 속도 개선 (CI 수행시간 20% 감소)

      - layout: left
        title: 테스트 수행 최적화 작업
        sub_title: 2022.10 ~ 2022.11, 2023.05 ~ 2023.06
        description: | # this will include new lines to allow paragraphs
          - 서비스에 존재하는 모든 테스트 코드를 Junit5로 마이그레이션 진행
          - 테스트 코드 수행 시간 지연 원인을 분석해 테스트 수행 시간 개선 (`4분 54초에서 2분 07초로 개선`)

      - title: Jenkin CI 빌드 구성 개선
        sub_title: 2022.10 ~ 2022.11
        description: | # this will include new lines to allow paragraphs
          - Jenkins CI를 Docker CI로 전환
          - Pipeline -> Multi-Branch Pipeline 전환

      - title: 업무 자동화
        sub_title: 2022.09 ~ 2022.10
        description: | # this will include new lines to allow paragraphs
          - Dooray! Hook API를 활용한 증적자료를 남기는 업무 자동화
          - 개발자의 개발 생산성 증가

      - title: Nginx를 이용한 서비스 개선
        sub_title: 2022.06. ~ 2022.08
        description: | # this will include new lines to allow paragraphs
          기존 nginx를 개선하여 다음과 같은 문제들을 해결하였습니다.
          - Reverse Proxy 설정을 통한 서비스 보안성 개선
          - HTTP Method Blocking을 통한 어뷰징 방지
          - access_log 분리를 통한 로그 관리 개선

      - title: 사내 오픈소스 starter 개발
        sub_title: 2022.04. ~ 2022.07
        description: | # this will include new lines to allow paragraphs
          - 외부 시스템에 대한 통신 검증을 하는 사내 오픈소스 Condition Checker starter 개발
          - starter 개발 이전 라이브러리 추가 개선 작업 수행
          - Autoconfiguration을 이용한 사내 오픈소스 starter library 개발
          - 기존 라이브러리를 starter로 변경하여 사용성 개선

      - title: Ucube 시스템 개발
        sub_title: 2021.01. ~ 2022.02
        description: | # this will include new lines to allow paragraphs
          - 사내 시스템 DA#을 이용한 ERD 설계
          - Sequence Diagram 및 API 설계 진행
          - Spring Boot, Java, JPA 및 QueryDSL를 활용한 서비스 개발
## Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
