# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박세환
title: Junior Backend Developer
email: gehwan96@gmail.com
website: www.github.com/Gelloger
blog: https://velog.io/@gehwan96
blog2: https://gelog.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Gelloger

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url: https://velog.io/@gehwan96

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
    안녕하세요. 백엔드 개발자로 일하고 있는 박세환입니다. 신기술과 최신 트렌드에 관심이 많고 새로운 기술을 배우는 것을 좋아합니다.
    개인뿐만 아니라 팀 전체의 생산성을 높이는 것에 관심이 많습니다.
    
    주 스킬은 <mark>Spring Boot</mark>이며, <mark>Java8/11</mark>를 사용하고 있습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: NHN CLOUD
        link: www.nhncloud.com/kr
        sub_title: Junior Backend Developer
        caption: 2022.02 ~ 현재
        description: | # this will include new lines to allow paragraphs
          Email 서비스를 담당하여 운영하고 있습니다. <br><br>
          기술 스택
            - <mark>Spring Boot</mark>,<mark>Nginx</mark>,<mark>RabbitMQ</mark>,<mark>Junit5</mark>, <mark>Java8/11</mark>, <mark>Javascript</mark>
            - <mark>Jenkins</mark>, <mark>Sonarqube</mark>, <mark>Grafana</mark>
            - <mark>Mybatis</mark>, <mark>MySQL</mark>, <mark>Git</mark>

      - title: LG CNS
        link: https://www.lgcns.com/
        sub_title: Junior Backend Developer
        caption: 2021.01. ~ 2022.01
        description: | # this will include new lines to allow paragraphs
          LG Uplus 서비스 Ucube 시스템의 단말기 판매 기능을 개발하였습니다.<br><br>
          기술 스택
            - <mark>Spring Boot</mark>, <mark>JPA</mark>
  - title: Experience # Title for the section
    layout: list # Layout for the section
    content:
      - title: Improving sending email structure
        sub_title: Email 발송 구조 개선
        caption: 2023.12 ~ 현재
        description: | # this will include new lines to allow paragraphs
          Email 발송 구조 개선 작업 수행 
          - SMTP Callback 구조 개선 (mq 도입)
          - 발송 로직 리팩토링 수행
      - title: Improving validation for Gmail sender policy changes
        sub_title: Gmail 발신자 정책 변경 대응
        caption: 2023.11 ~ 2023.12
        description: | # this will include new lines to allow paragraphs
          2024년 2월 Gmail 발신자 정책 변경에 따른 대응 작업을 수행
          - DMARC 검증 시나리오 추가
          - API 유효성 로직 추가
          - 발신자 도메인 검사로직 개선
          - PTR 레코드 설정 확인
      - title: Designing the Notification Hub API
        sub_title: 팀 내 신규 서비스 API 설계
        caption: 2023.07 ~ 2023.10
        description: | # this will include new lines to allow paragraphs
          신규 서비스 API 설계 참여
          - API 설계
          - OpenAPI specification을 이용한 API 문서화
      - title: 안정화 TF
        sub_title: 팀 내 발생하는 장애원인 분석 및 개선
        caption: 2023.08 ~ 2023.09
        description: | # this will include new lines to allow paragraphs
          팀 내에서 발생하는 장애 원인을 분석하고 개선하는 업무를 수행
          - 알람 개선
          - 전체 서비스 팀 내 공통 모듈 의존성 최신화
          - logging 카테고리 세분화를 통한 logNCrash 사용 고도화
          - sonarQube rule 적용
          - PR Template 제안 및 적용
          - Grafana 사용간 메트릭 지표 추가
      - layout: left
      - title: Configure Multi-Module
        sub_title: Gradle Migration
        caption: 2023.06 ~ 2023.07
        description: | # this will include new lines to allow paragraphs
          - Email 프로젝트를 멀티 모듈로 구성
          - 클래스를 공통화하여 중복되는 코드를 제거
          - 의존성 계층을 구분하여 의존성을 최소화
          - Maven에서 Gradle로 마이그레이션 진행 
          - 빌드 및 테스트 속도 개선 (CI 수행시간 20% 감소)
      - layout: left
        title: Optimize Test
        sub_title: 테스트 수행 최적화 작업
        caption: 2022.10 ~ 2022.11, 2023.05 ~ 2023.06
        description: | # this will include new lines to allow paragraphs
          - 서비스에 존재하는 모든 테스트 코드를 Junit5로 마이그레이션 진행
          - junit5 기능을 활용한 테스트 리팩토링 진행
          - 단위 테스트/CI 테스트를 분리해 환경간 테스트 수행 시간 최적화
          - 테스트 코드 수행 시간 지연을 분석해 수행 시간 개선 (`4분 54초에서 2분 07초로 개선`)
      - title: Convert Jenkins Build
        sub_title: Using MultiBranch Pipeline(Docker)
        caption: 2022.10 ~ 2022.11
        description: | # this will include new lines to allow paragraphs
          - Jenkins CI를 Docker CI로 전환
          - Pipeline -> Multi-Branch Pipeline 전환
      - title: Task Automation
        sub_title: 업무 자동화
        caption: 2022.09 ~ 2022.10
        description: | # this will include new lines to allow paragraphs
          - Dooray! Hook API를 활용한 증적자료를 남기는 업무 자동화
          - 개발자의 개발 생산성 증가
      - title: Improve Nginx
        sub_title: Nginx를 이용한 서비스 품질 개선
        caption: 2022.06. ~ 2022.08
        description: | # this will include new lines to allow paragraphs
          기존 nginx를 개선하여 다음과 같은 문제들을 해결하였습니다.
          - nginx exporter 설정을 통한 prometheus 메트릭 수집기능 개선
          - Reverse Proxy 설정을 통한 서비스의 보안성 개선
          - 일부 HTTP Method Blocking을 통한 어뷰징 방지
          - Nginx의 access_log 분리를 통한 로그 관리 개선
      - title: Manage Email Service
        sub_title: Email 서비스 관리
        caption: 2022.06. ~ 현재
        description: | # this will include new lines to allow paragraphs
          팀에서 Email 서비스를 담당하여 운영 중입니다. 다음과 같은 업무를 수행하고 있습니다.
          - 인프라 관리(ex) 서비스 이중화 구성, 모니터링 시스템 연동 등)
          - 고객 문의 대응 및 서비스 개선
          - 운영용 API 개발 및 기능 추가
          - 신규 기능 기획 및 개발
      - title: Developed an in-house open-source starter library
        sub_title: Autoconfiguration을 이용한 사내 오픈소스 starter 개발
        caption: 2022.04. ~ 2022.07
        description: | # this will include new lines to allow paragraphs
          - starter 개발 이전 라이브러리 추가 개선 작업 수행
          - Autoconfiguration을 이용한 사내 오픈소스 starter library 개발
          - 기존 라이브러리를 starter로 변경하여 사용성 개선
      - title: LG Uplus Ucube System
        sub_title: 단말기 판매 기능 개발
        caption: 2021.06. ~ 2022.01
        description: | # this will include new lines to allow paragraphs
          - 통신사 신규가입 인원을 대상으로 단말기를 판매 기능 개발
          - Sequence Diagram 및 API 설계 진행
          - Spring Boot, Java, JPA 및 QueryDSL 활용 
          

## Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
